// <auto-generated />
namespace KYC.EntitiesScratch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class riskItemlookups3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(riskItemlookups3));
        
        string IMigrationMetadata.Id
        {
            get { return "201502090051586_riskItemlookups3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
